language: cpp
sudo: true

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/tmp/icl ${ICL_OPTIONS} ..
  - make -j 3
  - make install

# define some yaml variables
include: &SIMPLE
  addons:
    apt:
      packages:
        - cmake
        - libpng-dev
        - libjpeg-dev
  env:
    - ICL_OPTIONS=""

include: &EXTENDED
  <<: *SIMPLE
  before_script:
    - sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl
    - sudo apt-get -qq update
    - sudo apt-get install -y libpcl-all
  addons:
    apt:
      packages:
        - cmake
        - libpng-dev
        - libjpeg-dev
        - ocl-icd-opencl-dev
        - libeigen3-dev
        - libopenni-dev
        - libopencv-dev
        - libmagick++-dev
        - qtbase5-dev
        - qtmultimedia5-dev
        - libqt5opengl5-dev
        - libfreenect-dev
        - libzmq-dev
        - libglew-dev
        - libusb-dev
        - libavcodec-dev
        - libavresample-dev 
        - libavdevice-dev 
        - libbullet-dev
  env:
    - ICL_OPTIONS="\
          -DBUILD_WITH_OPENCV=ON \
          -DBUILD_WITH_QT=ON \
          -DBUILD_WITH_OPENGL=ON \
          -DBUILD_WITH_EIGEN3=ON \
          -DBUILD_WITH_IMAGEMAGICK=ON \
          -DBUILD_WITH_LIBAV=ON \
          -DBUILD_WITH_LIBDC=ON \
          -DBUILD_WITH_LIBFREENECT=ON \
          -DBUILD_WITH_V4L=ON \
          -DBUILD_WITH_LIBUSB=ON \
          -DBUILD_WITH_ZMQ=ON \
          -DBUILD_WITH_OPENCL=ON \
          -DBUILD_WITH_OPENNI=ON \
          -DBUILD_WITH_PCL=ON \
          -DBUILD_WITH_BULLET=ON \
          -DBUILD_WITH_BULLET_OPTIONAL=ON \
          -DBUILD_EXAMPLES=ON \
          -DBUILD_DEMOS=ON \
          -DBUILD_APPS=ON"

include: &OSX
  env:
    - ICL_OPTIONS="\
          -DCMAKE_MODULE_PATH=/usr/local/share/cmake/Modules \
          -DBUILD_APPS=On \
          -DBUILD_DEMOS=On \
          -DBUILD_EXAMPLES=On \
          -DBUILD_WITH_OPENCV=On \
          -DBUILD_WITH_QT=On \
          -DQT_ROOT=/usr/local/opt/qt5 \
          -DBUILD_WITH_OPENGL=On \
          -DBUILD_WITH_IMAGEMAGICK=On \
          -DBUILD_WITH_LIBAV=On \
          -DBUILD_WITH_LIBDC=On \
          -DBUILD_WITH_EIGEN3=On \
          -DBUILD_TESTS=ON"

matrix:
  include:
    - <<: *SIMPLE
      compiler: gcc
    - <<: *EXTENDED
      compiler: gcc
    - <<: *EXTENDED
      compiler: clang
    - <<: *OSX
      os: osx
      before_script:
        - brew update
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install iclcv/homebrew-formulas/icl --only-dependencies || echo "dependency build returned non-zero"
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
        - brew link --force imagemagick@6
